import { ProjectItem } from '@/interface';

export const projectTableHeader = [
  'Name',
  'Live URL',
  'Source Code',
  'Tools',
  'Edit',
];

export const initProjectValue: ProjectItem = {
  id: '',
  images: '',
  title: '',
  content: '',
  slug: '',
  description: '',
  caption: '',
  tags: '',
  keywords: '',
  audio_url: '',
  published_datetime: '',
  is_comment_disabled: false,
  article_id: '',
  user_id: '',
  portfolio_id: '',
  seen_count: 0,
  comments_count: 0,
  liked_count: 0,
  is_published: false,
  word_count: 0,
  character_count: 0,
  reading_minutes: 1,
  technologies: '',
  github_repo: '',
  live_demo_url: '',
  video_url: '',
  contributors: '',
  licenses: '',
  dependencies: '',
  frameworks: '',
  platform: '',
  project_status: '',
  support_email: '',
  deployment_platform: '',
  deployment_status: '',
  certificate_url: '',
  demo_credentials: '',
};
